<?php 

/**
 * this class is auto generated by program
 * 
 * @package application.modules.products.components.AmazonHome 
 */
class AmazonBeauty extends AmazonUpload implements IAmazonUpload
{
	/**
	 * @inheritdoc
	 * @noreturn
	 */
	public function init()
	{
		parent::init();
	}	

    /**
     * 创建产品
     * @return bool
     */
    protected function createProduct()
    {
        $xmls = array();
        $data = $this->_getBaseInfo();
        $xsd2 = UebModel::model('AmazonProdataxsd')->findByPk($this->product->xsd_type[1]);

        if (empty($xsd2)) {
            throw new Exception ("Error Processing Request", 1);
        }
        //子分类方法名
        $method ='_'.$xsd2->category;
        $this->$method($xmls,$data);

        return true;
    }

	/**
	 * Beauty分类组装数据
	 * 
	 * @throws Exception
	 */
	public function _BeautyMisc($xmls,$data) 
	{       //单品
        if ($this->product->product_is_multi==0) {
            //指定产品分类
            $data['ProductData'] = array(
                'Beauty' => array(
                    'ProductType' =>array(
                    	'BeautyMisc' => array(
                    		'UnitCount' => array(
									'@unitOfMeasure' => "Count",
									'%' => "1",
									),
                    		),
                    	), 
                ),
            );
            $xmls[$this->product->sku] = $this->arr2xml->buildXML($this->removeEmptyItem($data),'Product');
        }
       	//多属性 
        else if ($this->product->product_is_multi==2) {
        	//父体变体设置
        	 $data['ProductData'] = array(
                'Beauty' => array(
                	'ProductType' => array(
                		'BeautyMisc' => array(
                    		'VariationData' => array(
                    			'Parentage' => 'parent',
                    			'VariationTheme' => $this->product->variation_theme,
                    			),
                    		),
                		),
                ),
            );
        	 $xmls[$this->product->sku] = $this->arr2xml->buildXML($this->removeEmptyItem($data),'Product');

        	//循环所有子sku产品
        	 foreach ($this->product->sonskues as $sonprd) {
        	 	//clone父体信息
        	 	$data['DescriptionData']['MfrPartNumber'] = $sonprd->mfr;
        	 	
				$child = $data;
				$variations = json_decode($sonprd->variations, true);
				$suffix     = sprintf('(%s)', implode('-', array_values($variations)));
				//修改子sku产品sku码
				unset($child['SKU']);
				unset($child['StandardProductID']);
				//在SKU后面添加StandardProductID
				$Sku_ProductID=array(
					'SKU' => $sonprd->seller_sku,
					'StandardProductID' => array(
						'Type' => $sonprd->standard_product_id_type,
						'Value' => $sonprd->standard_product_id,
						),
					);

				$child=array_merge($Sku_ProductID,$child);
				//修改子sku产品的标题
				$child['DescriptionData']['Title'] = $child['DescriptionData']['Title']. $suffix;
				
				//修改子sku变体内容
				$child['ProductData'] = array(
					'Beauty' => array(
						'ProductType' => array(
	                		'BeautyMisc' => array(
	                    		'VariationData' => array(
	                    			'Parentage' => 'child',
	                    			//指定和父体为相同的变体
	                    			'VariationTheme' => $this->product->variation_theme,
	                    			),
	                    		'UnitCount' => array(
									'@unitOfMeasure' => "Count",
									'%' => "1",
									),
                    			),
                			),
					),
				);

				foreach (array_keys($variations) as $name) {
					$child['ProductData']['Beauty']['ProductType']['BeautyMisc']['VariationData'][$name] = $variations[$name];
				}

				$xmls[$sonprd->sku] = $this->arr2xml->buildXML($this->removeEmptyItem($child), 'Product');
        	 }
        }

       //将其推到任务队列
		foreach ($xmls as $sku => $xml) {

			//检查是否已经在任务队列
			$found = UebModel::model('AmazonProductTask')->find(array(
				'condition' => 'account_id=:account_id AND amz_product_id=:amz_product_id AND sku=:sku AND type=:type',  
				'params' => array(
					':account_id' => $this->product->account_id,
					':amz_product_id' => $this->product->id,
					':sku'=> $sku,
					':type'=> self::PRODUCT,
					)
			));
			$model = !empty($found) ? $found : new AmazonProductTask();

			$model->flow_no = $this->genUniqidId();
			$model->account_id = $this->product->account_id;
			$model->amz_product_id = $this->product->id;
			$model->sku = $sku;
			$model->type = self::PRODUCT;
			$model->xml = $this->getRealXML(array($xml), SubmitFeedRequest::NEW_PRODUCT);
			$model->status = 1;
			$model->creator = Yii::app()->user->id?Yii::app()->user->id:$this->uid;
			$model->create_date = time();	

			$model->save();

			if (empty($model->id)) {
				throw new Exception("上传BeautyMisc分类产品异常", 1);
			}
		}
			//上传操作记录日志
			$log = new AmazonUpLog();

			$log->account_id = $this->product->account_id;
			$log->amz_product_id = $this->product->id;
			$log->operator = empty($found)?1:2;
			$log->title = empty($found)?"上传产品":"更新产品";
			$log->content = '';
			$log->type = self::PRODUCT;
			$log->num = 1;
			$log->creator = Yii::app()->user->id?Yii::app()->user->id:$this->uid;
			$log->create_date = time();

			$log->save();
			if (empty($log->id)) {
				throw new Exception("记录上传BeautyMisc分类产品日志异常", 1);
			}
	}

}
// end of class
