
<?php 

/**
 * this class is auto generated by program
 * 
 * @package application.modules.products.components.AmazonHome 
 */
class AmazonJewelry extends AmazonUpload implements IAmazonUpload
{
	/**
	 * @inheritdoc
	 * @noreturn
	 */
	public function init()
	{
		parent::init();
	}

	/**
	 * 根据子分类名映射相应的子分类方法处理
	 * @return string
	 */
	protected function categoryMethod($subcate) {
		$arr1 = array('Watch');
		$arr2 = array('FashionNecklaceBraceletAnklet');
		$arr3 = array('FashionRing','FashionOther','FashionEarring');
		$arr4 = array('FineNecklaceBraceletAnklet','FineRing','FineEarring');
		$arr5 = array('FineOther');

		if (in_array($subcate, $arr1)) {
			throw new Exception("Watch子分类暂未授权", 1);;
		} else if (in_array($subcate, $arr2)) {
			$method = '_subCategory2';
		} else if (in_array($subcate, $arr3)) {
			$method = '_subCategory3';
		} else if (in_array($subcate, $arr4)) {
			$method = '_subCategory4';
		} else if (in_array($subcate, $arr5)) {
			$method = '_subCategory5';
		}else {
			throw new Exception("{$subcate}子分类未定义", 1);
		}
		return $method;
	}
    /**
	 * 上传产品
	 *
	 * @return bool
	 */
	protected function createProduct()
	{
		$data = $this->_getBaseInfo();

		$xsd2 = UebModel::model('AmazonProdataxsd')->findByPk($this->product->xsd_type[1]);

		if (empty($xsd2)) {
			throw new Exception("缺少精确的XSD模板信息", 1);
		}

		$subcate = $xsd2->category;
		//获取分类方法名
		$method = $this->categoryMethod($subcate);

		$type = $this->product->product_is_multi;

		$data['ProductData'] = array(
			'Jewelry' => array(
				'ProductType' => array(
					$subcate => array(),
					),
				'Color' => 'default',
				'StyleName' => 'default',
				),
			);
		//单品
		if ($type == 0) {
			$array = $this->$method($type);
			$data['ProductData']['Jewelry']['ProductType'][$subcate] = $array;
			$xmls[$this->product->sku] = $this->arr2xml->buildXML($this->removeEmptyItem($data), 'Product');
		}
		//多属性
		else if ($type == 2) {
			//父体设置 $parentage 1为父体 2为子体
			$array = $this->$method($type,$parentage = 1);

			$data['ProductData']['Jewelry']['ProductType'][$subcate] = $array;
			$xmls[$this->product->sku] = $this->arr2xml->buildXML($this->removeEmptyItem($data), 'Product');

			foreach ($this->product->sonskues as $sonprd) {
				$data['DescriptionData']['MfrPartNumber'] = $sonprd->mfr;
				$child = $data;

				$variations = json_decode($sonprd->variations, true);
				$suffix     = sprintf('(%s)', implode('-', array_values($variations)));

				//修改子sku产品sku码
				$child['SKU'] = $sonprd->seller_sku;

				//修改子sku UPC码
				$child['StandardProductID']['Type']  = $sonprd['standard_product_id_type'];
				$child['StandardProductID']['Value'] = $sonprd['standard_product_id'];

				//修改子sku产品的标题
				$child['DescriptionData']['Title'] = $child['DescriptionData']['Title']. $suffix;

				$array = $this->$method($type,$parentage = 2);

				$child['ProductData']['Jewelry']['ProductType'][$subcate] = $array;
				$child['ProductData']['Jewelry']['Color'] = isset($variations['Color'])?$variations['Color']:$sonprd->seller_sku;
				$child['ProductData']['Jewelry']['StyleName'] = isset($variations['StyleName'])?$variations['StyleName']:$sonprd->seller_sku;

				$xmls[$sonprd->sku] = $this->arr2xml->buildXML($this->removeEmptyItem($child), 'Product');
			}
		}
		//将其推到任务队列
		foreach ($xmls as $sku => $xml) {
			//查找是否已经存在
			$found = UebModel::model('AmazonProductTask')->find("account_id=:aid AND amz_product_id=:id AND type=:type AND sku=:sku",
				array(
					':id' => $this->product->id,
					':aid' => $this->product->account_id,
					':type' => self::PRODUCT,
					':sku' => $sku,
					));

			$model = !empty($found) ? $found : new AmazonProductTask();

			$model->flow_no = $this->genUniqidId();
			$model->account_id = $this->product->account_id;
			$model->amz_product_id = $this->product->id;
			$model->sku = $sku;
			$model->type = self::PRODUCT;
			$model->xml = $this->getRealXML(array($xml), SubmitFeedRequest::NEW_PRODUCT);
			$model->status = 1;
			$model->creator = Yii::app()->user->id?Yii::app()->user->id:$this->uid;
			$model->create_date = time();	

			$model->save();

			if (empty($model->id)) {
				throw new Exception("保存{$sku}产品XML数据出错", 1);
			}
		}

		//记录日志
		$this->addLog(array(
			'account_id' => $this->product->account_id,
			'amz_product_id' => $this->product->id,
			'title' => empty($found) ? '添加产品' : '更新产品',
			'content' => '',
			'type' => self::PRODUCT,
			'num' => 1,
			'operator' => empty($found) ? 1 : 2,
		));

	}

	/**
	 * ('watch')分类组装数据
	 * 
	 * @throws Exception
	 */
	public function _subCategory1($type,$parentage)
	{       //单品
        if ($type == 0) {
            return array(
                    'MetalStamp' => 'default',
                    'GemType' => 'good',
                    'MovementType' => 'default',
                    'DisplayType' => 'default',
                    'DepartmentName' => 'womens',

	            	);
        }
       	//多属性 
        else if ($type == 2 && $parentage == 1) {
        	//父体数据
        	return array(
                    'VariationData' => array(
	                        'Parentage' => 'parent',
	                        'VariationTheme' => $this->product->variation_theme,
                    		),
                    'MetalStamp' => 'default',
                    'GemType' => 'good',
                    'MovementType' => 'default',
                    'DisplayType' => 'default',
                    'DepartmentName' => 'womens',
                    );
        }
        //子体数据 
        else if ($type == 2 && $parentage == 2) {
        	return array(
                    'VariationData' => array(
	                        'Parentage' => 'child',
	                        'VariationTheme' => $this->product->variation_theme,
                    		),
                    'MetalStamp' => 'default',
                    'GemType' => 'good',
                    'MovementType' => 'default',
                    'DisplayType' => 'default',
                    'DepartmentName' => 'womens',
	                );
        } else {
        	throw new Exception("分类产品数据异常", 1);
        }
	}

	/**
	 * ('FashionNecklaceBraceletAnklet')分类组装数据
	 * 
	 * @throws Exception
	 */
	public function _subCategory2($type,$parentage)
	{       //单品
        if ($type == 0) {
            return array(
                    'MetalStamp' => 'default',
                    'DepartmentName' => 'womens',
                    'GemType' => 'good',
	            	);
        }
       	//多属性 
        else if ($type == 2 && $parentage == 1) {
        	//父体数据
        	return array(
                    'VariationData' => array(
	                        'Parentage' => 'parent',
	                        'VariationTheme' => $this->product->variation_theme,
	                        'MetalType' => 'base',
                    		),
                    'MetalStamp' => 'default',
                    'DepartmentName' => 'womens',
                    'GemType' => 'good',
                    );
        }
        //子体数据 
        else if ($type == 2 && $parentage == 2) {
        	return array(
                    'VariationData' => array(
	                        'Parentage' => 'child',
	                        'VariationTheme' => $this->product->variation_theme,
	                        'MetalType' => 'base',
                    		),
                    'MetalStamp' => 'default',
                    'DepartmentName' => 'womens',
                    'GemType' => 'good',
	                );
        } else {
        	throw new Exception("分类产品数据异常", 1);
        }
	}

	/**
	 * ('FashionRing','FashionEarring','FashionOther','FineEarring','FineOther')分类组装数据
	 * 
	 * @throws Exception
	 */
	public function _subCategory3($type,$parentage)
	{       //单品
        if ($type == 0) {
            return array(

                    'MetalStamp' => 'default',
                    'DepartmentName' => 'womens',
	            	);
        }
       	//多属性 
        else if ($type == 2 && $parentage == 1) {
        	//父体数据
        	return array(
                    'VariationData' => array(
	                        'Parentage' => 'parent',
	                        'VariationTheme' => $this->product->variation_theme,
	                        'MetalType' => 'base',
                    		),
                    'MetalStamp' => 'default',
                    'DepartmentName' => 'womens',
                    );
        }
        //子体数据 
        else if ($type == 2 && $parentage == 2) {
        	return array(
                    'VariationData' => array(
	                        'Parentage' => 'child',
	                        'VariationTheme' => $this->product->variation_theme,
	                        'MetalType' => 'base',
                    		),
                    'MetalStamp' => 'default',
                    'DepartmentName' => 'womens',
	                );
        } else {
        	throw new Exception("分类产品数据异常", 1);
        }
	}

	/**
	 * ('FineNecklaceBraceletAnklet','FineRing','FineEarring')分类组装数据
	 * 
	 * @throws Exception
	 */
	public function _subCategory4($type,$parentage)
	{       //单品
        if ($type == 0) {
            throw new Exception("产品分类错误，请设置多属性产品重新推送", 1);
        }
       	//多属性 
        else if ($type == 2 && $parentage == 1) {
        	//父体数据
        	return array(
                    'VariationData' => array(
	                        'Parentage' => 'parent',
	                        'VariationTheme' => $this->product->variation_theme,
	                        'MetalType' => 'base',
                    		),
                    'MetalStamp' => 'default',
                    'DepartmentName' => 'womens',
                    );
        }
        //子体数据 
        else if ($type == 2 && $parentage == 2) {
        	return array(
                    'VariationData' => array(
	                        'Parentage' => 'child',
	                        'VariationTheme' => $this->product->variation_theme,
	                        'MetalType' => 'base',
                    		),
                    'MetalStamp' => 'default',
                    'DepartmentName' => 'womens',
	                );
        } else {
        	throw new Exception("分类产品数据异常", 1);
        }
    }

    /**
	 * ('FineOther')分类组装数据
	 * 
	 * @throws Exception
	 */
	protected function _subCategory5($type,$parentage)
	{       //单品
        if ($type == 0) {
            throw new Exception("产品分类错误，请设置多属性产品重新推送", 1);
        }
       	//多属性 
        else if ($type == 2 && $parentage == 1) {
        	//父体数据
        	return array(
                    'VariationData' => array(
	                        'Parentage' => 'parent',
	                        'VariationTheme' => 'StyleName',
	                        'MetalType' => 'base',
                    		),
                    'MetalStamp' => 'default',
                    'DepartmentName' => 'womens',
                    );
        }
        //子体数据 
        else if ($type == 2 && $parentage == 2) {
        	return array(
                    'VariationData' => array(
	                        'Parentage' => 'child',
	                        'VariationTheme' => 'StyleName',
	                        'MetalType' => 'base',
                    		),
                    'MetalStamp' => 'default',
                    'DepartmentName' => 'womens',
	                );
        } else {
        	throw new Exception("分类产品数据异常", 1);
        }
	}

	
}
// end of class
